## Image Representation

An image is represented inside a computer as a collection of **numbers**.

Each small unit of an image is called a **pixel**. The pixel contains a numerical value that represents the brightness or color of that location.

For a grayscale image, a pixel usually has a value from **0 to 255**:

- `0` → Black
- `255` → White
- Values between `0` and `255` → Different shades of gray

For a color image, each pixel contains values from different **channels**, such as Red, Green, and Blue.

So the basic process is:

**Image → Pixels → Numerical Values → Tensor → CNN**

### Real-World Example

Consider a photo of a **car**.

A human sees:

> "This is a car."

But a CNN does not directly see the car as a human does. It receives numerical pixel values.

The CNN processes those values and gradually learns patterns such as:

```text
Pixels
  ↓
Edges
  ↓
Shapes
  ↓
Parts of the car
  ↓
Complete car
```

This is why understanding image representation is important before learning convolution.

### Why do we need this?

CNNs can only perform mathematical operations on numerical data. Therefore, an image must first be represented using numbers before it can be given to a neural network.

In [1]:
## Python Example

import numpy as np

image = np.array([
    [0, 0, 255],
    [0, 255, 255],
    [255, 255, 0]
])

print(image)
print("Image shape:", image.shape)


[[  0   0 255]
 [  0 255 255]
 [255 255   0]]
Image shape: (3, 3)


```

### Output

```text
[[  0   0 255]
 [  0 255 255]
 [255 255   0]]

Image shape: (3, 3)
```

Here:

- The image has **3 rows**
- The image has **3 columns**
- Therefore, it contains **9 pixels**
- Each number represents the brightness of one pixel

For example:

```text
0   → Black
255 → White
```

This simple NumPy array is the basic idea behind how an image can be represented numerically.

## Topic 2 — Pixels
A **pixel** is the smallest individual unit of a digital image.

An image is made up of many pixels arranged in **rows and columns**.

Each pixel stores a numerical value.

For a grayscale image, the value usually ranges from **0 to 255**:

- `0` → Black
- `255` → White
- `128` → Gray
- Other values → Different shades of gray

For example, a 3 × 3 image contains:

**3 × 3 = 9 pixels**

```text
[  0   50  255
 100  150  200
 255  200   20 ]
```

Each number represents one pixel.

In a color image, a pixel contains multiple values because it has multiple channels. For example, an RGB pixel can contain:

```text
[R, G, B]
```

So, pixels are the basic numerical information from which a CNN learns image patterns.

### Real-World Example

Consider a photograph taken using a mobile phone.

A small image might contain thousands or millions of pixels.

When you zoom into the photograph, you can eventually see tiny individual squares. Each square represents a pixel.

A CNN processes these pixel values to identify patterns such as **edges, textures, and shapes**.

### Why do we need to understand pixels?

Convolution operates directly on groups of pixel values.

For example:

```text
Image pixels
     ↓
Small region of pixels
     ↓
Kernel operates on them
     ↓
New value
     ↓
Feature map
```

Therefore, understanding pixels is essential for understanding how convolution works.

In [2]:
## Python Example

import numpy as np

image = np.array([
    [0, 50, 255],
    [100, 150, 200],
    [255, 200, 20]
])

print(image)

print("Number of pixels:", image.size)
print("Pixel at row 1, column 2:", image[1, 2])


[[  0  50 255]
 [100 150 200]
 [255 200  20]]
Number of pixels: 9
Pixel at row 1, column 2: 200


Here:

- `image.size` → total number of pixels
- `image[1, 2]` → gets the pixel at row `1`, column `2`
- Its value is `150`, which represents a shade of gray

## Channels

A **channel** contains one type of information about an image.

The number of channels depends on the type of image.

### Grayscale Image

A grayscale image has **1 channel**.

Each pixel contains one value representing brightness.

```text
Grayscale
   ↓
1 channel
   ↓
Brightness
```

### RGB Color Image

An RGB image has **3 channels**:

- **R** → Red
- **G** → Green
- **B** → Blue

Each pixel has three values:

```text
[R, G, B]
```

For example:

```text
[255, 0, 0]
```

represents strong red.

The three channels are stored separately:

```text
Red Channel     Green Channel     Blue Channel
    ↓                 ↓                ↓
   image             image            image
```

The CNN receives these channels together as the input image.

For example, an RGB image with height `224` and width `224` has:

```text
3 × 224 × 224
```

values.

In PyTorch CNNs, the common image tensor format is:

```text
Channels × Height × Width
```

For a batch of images:

```text
Batch × Channels × Height × Width
```

### Real-World Example

Think about a mobile phone camera taking a photo of a **red car**.

The image contains information about:

- How much red is present
- How much green is present
- How much blue is present

The CNN processes these channels together to learn useful patterns such as the car's edges, colors, and shapes.

### Why do we need channels?

Channels allow a CNN to receive different types of visual information.

For grayscale images, one channel is enough.

For color images, multiple channels preserve the color information needed by the CNN.

In [3]:
## Python Example

import numpy as np

# Grayscale image
gray_image = np.zeros((4, 4))

# RGB image
rgb_image = np.zeros((3, 4, 4))

print("Grayscale shape:", gray_image.shape)
print("RGB shape:", rgb_image.shape)


Grayscale shape: (4, 4)
RGB shape: (3, 4, 4)


Here:

```text
Grayscale → (Height, Width)
RGB       → (Channels, Height, Width)
```

So:

```text
(4, 4)
```

means a grayscale image with 4 × 4 pixels.

And:

```text
(3, 4, 4)
```

means an RGB image with:

- 3 channels
- 4 pixels high
- 4 pixels wide

The `3` represents **Red, Green, and Blue**.

## Grayscale vs RGB

Images can be represented using different numbers of channels. Two common types are **grayscale** and **RGB**.

### Grayscale Image

A grayscale image contains only **one channel**.

Each pixel represents brightness:

```text
0   → Black
255 → White
```

Example:

```text
[  0  100  200  255 ]
```

A grayscale image does not contain separate red, green, and blue information.

Its shape is commonly represented as:

```text
Height × Width
```

For example:

```text
28 × 28
```

means 28 pixels high and 28 pixels wide.

### RGB Image

An RGB image contains **three channels**:

```text
R → Red
G → Green
B → Blue
```

Each pixel contains three values.

For example:

```text
[255, 0, 0]
```

represents red.

The three channels together create the final color image.

Its shape is commonly represented in PyTorch as:

```text
Channels × Height × Width
```

For example:

```text
3 × 224 × 224
```

### Main Difference

| Grayscale | RGB |
|---|---|
| 1 channel | 3 channels |
| Brightness information | Color information |
| Less data | More data |
| Suitable for many black-and-white images | Suitable for color images |

### Real-World Example

A **scanned document** can often be represented as grayscale because we mainly care about the text and brightness.

A **photograph of a person** normally uses RGB because color information is important.

### Why do we need to understand this?

The number of channels affects the input expected by a CNN.

For example:

```text
Grayscale image → 1 input channel
RGB image       → 3 input channels
```

Therefore, when creating a CNN, we must know how many channels the input image contains.

In [4]:
## Python Example

import numpy as np

# Grayscale image
gray_image = np.zeros((4, 4))

# RGB image
rgb_image = np.zeros((3, 4, 4))

print("Grayscale shape:", gray_image.shape)
print("RGB shape:", rgb_image.shape)


Grayscale shape: (4, 4)
RGB shape: (3, 4, 4)


## Image Tensors

A **tensor** is a data structure used by deep learning frameworks such as PyTorch to store numerical data.

An image can be converted into a tensor so that a CNN can process it.

For a grayscale image, the basic structure is:

```text
Height × Width
```

For an RGB image, we have three channels:

```text
Channels × Height × Width
```

For example:

```text
3 × 224 × 224
```

means:

- `3` → RGB channels
- `224` → image height
- `224` → image width

When multiple images are processed together, we add a **batch dimension**:

```text
Batch × Channels × Height × Width
```

For example:

```text
32 × 3 × 224 × 224
```

means:

- `32` → 32 images
- `3` → RGB channels
- `224` → height
- `224` → width

This is the common image format used by PyTorch CNNs.

### Real-World Example

Suppose we want to classify **32 cat and dog images** at the same time.

Each image is RGB and has a size of 224 × 224.

The input tensor can have the shape:

```text
32 × 3 × 224 × 224
```

The CNN receives this tensor and processes the images together.

### Why do we need image tensors?

CNN layers such as convolution expect numerical tensor input.

Therefore:

```text
Image
  ↓
Pixel values
  ↓
Tensor
  ↓
CNN
```

Converting images into tensors is what allows PyTorch to perform mathematical operations on them.

In [5]:
## Python Example

import torch

# One RGB image
image = torch.zeros(3, 4, 4)

print("Image shape:", image.shape)

# Batch of 8 RGB images
images = torch.zeros(8, 3, 4, 4)

print("Batch shape:", images.shape)


Image shape: torch.Size([3, 4, 4])
Batch shape: torch.Size([8, 3, 4, 4])


The first tensor represents:

```text
3 × 4 × 4
↓
RGB × Height × Width
```

The second tensor represents:

```text
8 × 3 × 4 × 4
↓
Batch × RGB × Height × Width
```

This `Batch × Channels × Height × Width` structure is very important when working with CNNs in PyTorch.

## Convolution

**Convolution** is the main operation used by a CNN to extract useful patterns from an image.

A CNN takes a small matrix called a **kernel (filter)** and moves it across the image.

At each position:

1. The kernel looks at a small region of the image.
2. The corresponding values are multiplied.
3. The multiplied values are added together.
4. The result becomes one value in the **feature map**.

### Simple Example

Suppose the input image contains:

```text
[ 1  2  3
  4  5  6
  7  8  9 ]
```

And the kernel is:

```text
[ 1  0
  0  1 ]
```

The kernel first looks at:

```text
[ 1  2
  4  5 ]
```

We multiply corresponding values:

```text
(1 × 1) + (2 × 0) + (4 × 0) + (5 × 1)
```

Result:

```text
1 + 0 + 0 + 5 = 6
```

That `6` becomes one value in the output feature map.

The kernel then moves to another position and repeats the same operation.

### Complete Flow

```text
Input Image
     ↓
Small Image Region
     ↓
Kernel
     ↓
Multiply + Add
     ↓
One Output Value
     ↓
Repeat Across Image
     ↓
Feature Map
```

### What does convolution learn?

During CNN training, the kernel values are **learned automatically**.

Different learned kernels can detect different patterns such as:

- Edges
- Lines
- Corners
- Textures
- More complex shapes

### Real-World Example

Imagine a CNN processing a photograph of a **car**.

An early convolution layer may learn filters that detect simple edges.

Later layers combine these patterns to detect:

```text
Edges
 ↓
Wheels / windows / lights
 ↓
Car parts
 ↓
Complete car
```

### Why do we need convolution?

A normal fully connected network would have difficulty efficiently processing large images because there can be a huge number of pixels.

Convolution allows the CNN to examine **small local regions** and learn useful visual patterns efficiently.

In [6]:
## Python Example

import numpy as np

image = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

kernel = np.array([
    [1, 0],
    [0, 1]
])

region = image[0:2, 0:2]

result = np.sum(region * kernel)

print("Image:")
print(image)

print("\nKernel:")
print(kernel)

print("\nSelected region:")
print(region)

print("\nConvolution result:", result)


Image:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Kernel:
[[1 0]
 [0 1]]

Selected region:
[[1 2]
 [4 5]]

Convolution result: 6


```

### Output

```text id="6x6jsu"
Image:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Kernel:
[[1 0]
 [0 1]]

Selected region:
[[1 2]
 [4 5]]

Convolution result: 6
```

The important calculation is:

```text
(1 × 1) + (2 × 0) + (4 × 0) + (5 × 1)
= 6
```

This is the basic operation that is repeated across the image to create a **feature map**.

## Kernels / Filters

A **kernel**, also called a **filter**, is a small matrix of numbers that moves across an image during convolution.

For example, a simple 3 × 3 kernel can look like:

```text
[ 1  0 -1
  1  0 -1
  1  0 -1 ]
```

The kernel examines a small region of the image at a time.

It performs:

**Multiply corresponding values → Add them → Produce one output value**

The kernel then moves to the next position and repeats the operation.

### What does a kernel detect?

Different kernels can detect different visual patterns.

For example:

- A kernel can learn to detect **vertical edges**
- Another can detect **horizontal edges**
- Another can detect **corners**
- Others can learn more complex textures and patterns

In a real CNN, we normally **do not manually choose the final kernel values**.

During training, the CNN learns useful kernel values from the training images.

### Kernel vs Filter

These terms are often used interchangeably.

For beginner-level understanding:

```text
Kernel = small matrix of weights
Filter = kernel used to detect a pattern
```

### Important Point

A kernel does **not** look at the entire image at once.

It looks at a small local region and slides across the image.

```text
Image
 ↓
Small region
 ↓
Kernel
 ↓
Multiply + Add
 ↓
Output value
```

Repeating this operation produces a **feature map**.

### Real-World Example

Imagine looking for **vertical edges** in a photograph.

A filter can learn to respond strongly when it finds a vertical boundary, such as:

```text
Building wall
      |
      |
      |
```

The filter produces higher values in locations where that pattern is present.

During CNN training, the network learns which filters are useful for the particular image-classification task.

### Why do we need kernels?

The kernel is the mechanism that allows a CNN to **extract visual patterns from pixels**.

Without kernels and convolution, the CNN would not have this efficient way of discovering local image features.

In [7]:
## Python Example

import numpy as np

image = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

kernel = np.array([
    [1, 0],
    [0, 1]
])

print("Image:")
print(image)

print("\nKernel:")
print(kernel)


Image:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Kernel:
[[1 0]
 [0 1]]


## Stride

**Stride** is the number of pixels the kernel moves at each step while performing convolution.

The most common stride is:

```text
Stride = 1
```

This means the kernel moves **one pixel at a time**.

### Stride = 1

Suppose we have:

```text id="n5zqbd"
Input: 5 × 5
Kernel: 3 × 3
Stride: 1
```

The kernel moves like this:

```text id="3m2xvf"
Position 1 → Position 2 → Position 3
      ↓
Next row
      ↓
Position 4 → Position 5 → Position 6
```

Because the kernel moves one pixel at a time, it examines many overlapping regions.

### Stride = 2

If:

```text id="az2w6q"
Stride = 2
```

the kernel moves **two pixels at a time**.

```text id="c8t3eg"
Position 1 → skip one pixel → Position 2
```

This produces a smaller feature map compared with stride 1.

### Effect of Stride

A larger stride generally means:

```text id="2uxl8t"
Larger stride
     ↓
Fewer kernel positions
     ↓
Smaller feature map
```

A smaller stride means:

```text id="11ctc4"
Smaller stride
     ↓
More kernel positions
     ↓
Larger feature map
```

### Real-World Example

Imagine scanning a large photograph with a small window.

If you move the window **one step at a time**, you inspect many overlapping areas.

If you move it **two steps at a time**, you inspect fewer areas and finish faster.

The kernel behaves in a similar way during convolution.

### Why do we need stride?

Stride controls **how far the kernel moves** across the image.

It therefore affects:

- How many locations are examined
- The size of the feature map
- The amount of computation

In CNNs, stride is often used to gradually reduce the spatial size of feature maps.

In [8]:
## Python Example

import numpy as np

image = np.zeros((5, 5))
kernel_size = 3

# Stride 1
output_size_1 = (5 - kernel_size) // 1 + 1

# Stride 2
output_size_2 = (5 - kernel_size) // 2 + 1

print("Output size with stride 1:", output_size_1)
print("Output size with stride 2:", output_size_2)


Output size with stride 1: 3
Output size with stride 2: 2


```

### Output

```text id="v2l2bq"
Output size with stride 1: 3
Output size with stride 2: 2
```

So:

```text id="7k7c3k"
Input: 5 × 5
Kernel: 3 × 3

Stride 1 → Output: 3 × 3
Stride 2 → Output: 2 × 2
```

The larger stride causes the kernel to make fewer movements, resulting in a smaller feature map.

## Padding

**Padding** means adding extra pixels around the border of an image before performing convolution.

Usually, the added pixels have a value of `0`, so this is called **zero padding**.

### Why is padding needed?

Without padding, the kernel cannot fully cover the edges of the image.

For example:

```text id="8a6b7k"
Input: 5 × 5
Kernel: 3 × 3
Padding: 0
Stride: 1
```

The output becomes:

```text id="7qzqtc"
3 × 3
```

So the feature map becomes smaller.

With padding:

```text id="s3uj0a"
Input: 5 × 5
Padding: 1
```

The image becomes effectively:

```text id="2nq1n5"
7 × 7
```

Then a 3 × 3 kernel can produce:

```text id="wq1s1y"
7 × 7 → 3 × 3 → 5 × 5
```

So padding can help preserve the spatial size.

### Simple Visualization

Original image:

```text id="c8s9t7"
[ 1 2 3
  4 5 6
  7 8 9 ]
```

After padding of 1:

```text id="h0m5vo"
[ 0 0 0 0 0
  0 1 2 3 0
  0 4 5 6 0
  0 7 8 9 0
  0 0 0 0 0 ]
```

The `0`s are the padding pixels.

### Common Padding Values

**Padding = 0**

No extra pixels are added.

**Padding = 1**

One layer of pixels is added around the image.

### Real-World Example

Imagine a kernel scanning an image of a **person**.

Important information may exist near the image boundary, such as the edge of a person's face or body.

Without padding, these boundary regions are used less frequently.

Padding gives the kernel additional space around the border so that edge information can be processed properly.

### Why do we need padding?

Padding helps:

- Preserve image dimensions
- Process boundary pixels
- Prevent feature maps from shrinking too quickly
- Allow deeper CNN architectures

A common CNN design uses:

```text id="v5h8yo"
Padding = 1
Kernel = 3 × 3
Stride = 1
```

This can keep the height and width unchanged.

In [9]:
## Python Example

import numpy as np

image = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

padded_image = np.pad(
    image,
    pad_width=1,
    mode="constant",
    constant_values=0
)

print("Original image:")
print(image)

print("\nPadded image:")
print(padded_image)


Original image:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded image:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


### Output

Original image:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded image:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]
```

The original image was **3 × 3**.

After padding of `1`, it becomes **5 × 5**.

```text id="f9p8qr"
3 × 3 → Padding 1 → 5 × 5
```

The extra border allows the convolution kernel to process the original image's boundary regions.

## Receptive Field

The **receptive field** is the area of the original image that a particular neuron or feature-map value can "see".

In simple words:

> **Receptive field = the part of the input image that influences one output value.**

### Simple Example

Suppose we have:

```text
Input image: 5 × 5
Kernel: 3 × 3
Stride: 1
```

One value in the feature map is calculated using a **3 × 3 region** of the input.

Therefore, that output value has a:

```text
3 × 3 receptive field
```

For example:

```text id="g9xj4a"
Input Image

[ 1  2  3  4  5
  6  7  8  9 10
 11 12 13 14 15
 16 17 18 19 20
 21 22 23 24 25 ]

        ↓

One output value
        ↑
Uses this region:

[ 7  8  9
 12 13 14
 17 18 19 ]
```

So that particular output value depends on those **9 input pixels**.

### Why does receptive field matter?

A small receptive field can detect **small local patterns**, such as:

- Edges
- Lines
- Corners
- Small textures

As we go deeper into a CNN, neurons can indirectly see a **larger portion of the original image**.

For example:

```text id="u5b9bh"
Early layer
Small receptive field
      ↓
Edges

Deeper layer
Larger receptive field
      ↓
Shapes

Even deeper layer
Much larger receptive field
      ↓
Object parts
```

This allows CNNs to move from simple visual patterns to more complex patterns.

### Real-World Example

Consider a CNN analyzing a **face**.

An early layer may only see a small area and detect an edge.

A deeper layer may see a larger area containing several edges and recognize something like an **eye**.

An even deeper layer may see a much larger area and recognize a combination of facial features.

So, deeper CNN layers generally have access to more surrounding image information.

### Why do we need to understand receptive field?

It explains **how much of the original image influences what a CNN learns at different layers**.

It is one reason CNNs can gradually learn:

```text
Pixels → Edges → Shapes → Parts → Objects
```

In [10]:
## Python Example

import numpy as np

image = np.arange(1, 26).reshape(5, 5)

# Select a 3 × 3 region
region = image[1:4, 1:4]

print("Image:")
print(image)

print("\nReceptive field:")
print(region)


Image:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Receptive field:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


```

### Output

```text id="n9r5hd"
Image:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Receptive field:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
```

Here, the selected **3 × 3 region** represents the receptive field for one output value when using a 3 × 3 kernel.

So:

```text id="zqv9pu"
One output value
       ↑
       |
3 × 3 input region
```

This is the basic idea of a receptive field.

## Pooling

**Pooling** is a downsampling operation used in CNNs to reduce the spatial size of feature maps.

It looks at a small region of the feature map and replaces that region with a single value.

The two common types are:

- **Max Pooling** → takes the largest value
- **Average Pooling** → takes the average value

### Max Pooling

Suppose we have:

```text id="v9h2qr"
[ 1  3
  2  4 ]
```

With max pooling:

```text id="8h6z4r"
Maximum = 4
```

So the entire 2 × 2 region becomes:

```text id="q9w8ex"
[ 4 ]
```

### Why does pooling reduce size?

Suppose the feature map is:

```text id="h4j0dy"
4 × 4
```

Using a:

```text id="6y3lna"
2 × 2 pooling window
Stride = 2
```

the output becomes:

```text id="x3k9pa"
2 × 2
```

So:

```text id="5c8yqv"
4 × 4 → 2 × 2
```

### What does pooling preserve?

Max pooling keeps the **strongest activation** in a region.

If a convolution filter detects an edge strongly in one part of the region, max pooling keeps that strong response.

### Real-World Example

Imagine a CNN detecting a **car wheel**.

A feature map may contain strong values around the wheel.

Pooling reduces the size of the feature map while keeping the important strong responses.

This helps the network focus on important features without processing every location at the original resolution.

### Why do we need pooling?

Pooling helps:

- Reduce feature-map size
- Reduce computation
- Reduce the amount of data passed to later layers
- Keep strong feature responses

A common CNN flow is:

```text id="t5q0xk"
Image
  ↓
Convolution
  ↓
Feature Map
  ↓
Pooling
  ↓
Smaller Feature Map
```

Pooling is therefore mainly used for **downsampling**.

In [11]:
## Python Example

import numpy as np

feature_map = np.array([
    [1, 3, 2, 4],
    [5, 6, 1, 2],
    [7, 2, 8, 3],
    [4, 1, 5, 9]
])

pooled = np.zeros((2, 2))

for i in range(2):
    for j in range(2):

        region = feature_map[
            i*2:i*2+2,
            j*2:j*2+2
        ]

        pooled[i, j] = np.max(region)

print("Original Feature Map:")
print(feature_map)

print("\nAfter Max Pooling:")
print(pooled)


Original Feature Map:
[[1 3 2 4]
 [5 6 1 2]
 [7 2 8 3]
 [4 1 5 9]]

After Max Pooling:
[[6. 4.]
 [7. 9.]]


```

### Output

```text id="q1z8py"
Original Feature Map:
[[1 3 2 4]
 [5 6 1 2]
 [7 2 8 3]
 [4 1 5 9]]

After Max Pooling:
[[6. 4.]
 [7. 9.]]
```

For example, the first region is:

```text id="o3jv6z"
[1 3
 5 6]
```

The maximum value is:

```text id="y4w7cu"
6
```

The same process is repeated for the other regions.

Therefore:

```text id="h7v4qa"
4 × 4 Feature Map
        ↓
2 × 2 Max Pooling
        ↓
2 × 2 Feature Map
```

## Flattening

**Flattening** means converting a multi-dimensional feature map into a **single one-dimensional vector**.

CNN layers such as convolution and pooling produce feature maps with dimensions like:

```text
Channels × Height × Width
```

Before passing these features to a traditional **fully connected layer**, we often flatten them.

### Simple Example

Suppose a CNN produces:

```text
2 × 2
```

feature map:

```text
[ 1  2
  3  4 ]
```

After flattening:

```text
[1, 2, 3, 4]
```

So:

```text
2 × 2 → 4 values
```

For multiple channels, suppose we have:

```text
2 × 2 × 3
```

That contains:

```text
2 × 2 × 3 = 12 values
```

After flattening:

```text
12 values → 1D vector
```

### CNN Flow

```text
Input Image
     ↓
Convolution
     ↓
Feature Maps
     ↓
Pooling
     ↓
Smaller Feature Maps
     ↓
Flatten
     ↓
1D Vector
     ↓
Fully Connected Layer
```

Flattening **does not learn anything** by itself. It simply changes the shape of the data.

### Real-World Example

Suppose a CNN processes an image of a **cat**.

After several convolution and pooling layers, the network may have extracted useful features such as edges, ears, eyes, and fur patterns.

These features are still arranged spatially in feature maps.

Flattening converts them into one long list of values so that the fully connected layer can use them for the final prediction.

### Why do we need flattening?

A fully connected layer expects its input as a vector of values.

Flattening connects the **CNN feature extraction part** with the **classification part**.

```text
Feature Maps
     ↓
Flatten
     ↓
Vector
     ↓
Fully Connected Layer
```

In [12]:
## Python Example

import numpy as np

feature_map = np.array([
    [1, 2],
    [3, 4]
])

flattened = feature_map.flatten()

print("Feature Map:")
print(feature_map)

print("\nFlattened:")
print(flattened)

print("\nShape before:", feature_map.shape)
print("Shape after:", flattened.shape)


Feature Map:
[[1 2]
 [3 4]]

Flattened:
[1 2 3 4]

Shape before: (2, 2)
Shape after: (4,)



### Output
Feature Map:
[[1 2]
 [3 4]]

Flattened:
[1 2 3 4]

Shape before: (2, 2)
Shape after: (4,)
```

So:

```text
2 × 2
  ↓
Flatten
  ↓
4 values
```

In a real CNN, the feature maps can contain many more values, but the idea is exactly the same.

## Fully Connected Layers

A **Fully Connected (FC) layer**, also called a **Linear layer**, connects every input value to the neurons in the next layer.

In a CNN, convolution and pooling are mainly responsible for **extracting features**.

The fully connected layer uses those extracted features to make the **final prediction**.

### Simple Flow

```text id="v3z4sa"
Image
  ↓
Convolution
  ↓
Feature Maps
  ↓
Pooling
  ↓
Flatten
  ↓
Fully Connected Layer
  ↓
Prediction
```

Suppose flattening produces:

```text id="y7x2ap"
[0.2, 0.8, 0.4, 0.6]
```

These values are given to a fully connected layer.

The layer performs mathematical operations using **weights and bias** and produces new values.

For a classification problem, the final layer may produce one output for each class.

For example:

```text id="2h3z9c"
Cat   → 0.85
Dog   → 0.15
```

The model would predict **Cat** because it has the higher score.

### What does the fully connected layer learn?

It learns how to combine the features extracted by the convolution layers.

For example:

```text id="4f1h8s"
Convolution layers
       ↓
Detect edges
       ↓
Detect shapes
       ↓
Detect object parts
       ↓
Flatten
       ↓
Fully Connected Layer
       ↓
Combine features
       ↓
Final prediction
```

### Real-World Example

Suppose a CNN is trained to classify **cats and dogs**.

The convolution layers may detect:

- Ears
- Eyes
- Fur patterns
- Face shapes

After flattening, these detected features are passed to the fully connected layer.

The fully connected layer combines them and produces the final classification:

```text id="9n5x2q"
Cat → higher score
Dog → lower score
```

### Why do we need fully connected layers?

The convolution layers are good at **extracting visual features**, while the fully connected layers help use those features for the final task.

So, a simple CNN can be understood as:

```text id="3u8k1v"
Feature Extraction
       ↓
Convolution + Pooling
       ↓
Feature Representation
       ↓
Flatten
       ↓
Classification
       ↓
Fully Connected Layer
```

This completes the basic CNN pipeline:

**Image → Pixels → Tensor → Convolution → Kernel → Feature Map → Pooling → Flatten → Fully Connected Layer → Prediction**

In [13]:
## Python Example

#In PyTorch, a fully connected layer is commonly created using `nn.Linear`.


import torch
import torch.nn as nn

# 4 input features → 2 output neurons
layer = nn.Linear(4, 2)

x = torch.tensor([[0.2, 0.8, 0.4, 0.6]])

output = layer(x)

print("Input shape:", x.shape)
print("Output shape:", output.shape)
print("Output:", output)


Input shape: torch.Size([1, 4])
Output shape: torch.Size([1, 2])
Output: tensor([[-0.1140, -0.1980]], grad_fn=<AddmmBackward0>)


```

### Output

The exact output values can differ because the layer's weights are initialized automatically.

The important shapes are:

```text id="w0m7dn"
Input:
1 × 4

      ↓

Fully Connected Layer
4 input features → 2 neurons

      ↓

Output:
1 × 2
```

Here:

- `4` → number of input features
- `2` → number of output neurons
- `nn.Linear(4, 2)` → fully connected layer

In a CNN, these input features normally come from the **flattened feature maps**.

## Manual Convolution

A convolution operation takes a small **kernel** and moves it across the input image.

At every position:

```text
1. Select a small region
2. Multiply region × kernel
3. Add all values
4. Store the result
5. Move the kernel
6. Repeat
```

Consider this input image:

```text
[ 1  2  3
  4  5  6
  7  8  9 ]
```

And this kernel:

```text
[ 1  0
  0  1 ]
```

### Step 1 — First Position

The kernel starts at the top-left:

```text
Image region:

[ 1  2
  4  5 ]

Kernel:

[ 1  0
  0  1 ]
```

Multiply corresponding values:

```text
(1 × 1) = 1
(2 × 0) = 0
(4 × 0) = 0
(5 × 1) = 5
```

Add them:

```text
1 + 0 + 0 + 5 = 6
```

First feature-map value:

```text
6
```

### Step 2 — Move Right

The kernel moves one position to the right:

```text
[ 2  3
  5  6 ]
```

Calculation:

```text
(2 × 1) + (3 × 0) + (5 × 0) + (6 × 1)
= 8
```

Second value:

```text
8
```

### Step 3 — Move Down

The kernel returns to the left and moves down:

```text
[ 4  5
  7  8 ]
```

Calculation:

```text
(4 × 1) + (5 × 0) + (7 × 0) + (8 × 1)
= 12
```

Third value:

```text
12
```

### Step 4 — Final Position

The kernel moves right:

```text
[ 5  6
  8  9 ]
```

Calculation:

```text
(5 × 1) + (6 × 0) + (8 × 0) + (9 × 1)
= 14
```

Final value:

```text
14
```

### Final Feature Map

Therefore:

```text
Input Image

[ 1  2  3
  4  5  6
  7  8  9 ]

       ↓

Kernel

[ 1  0
  0  1 ]

       ↓

Convolution

       ↓

Feature Map

[  6   8
  12  14 ]
```

This is the fundamental operation behind CNN convolution.

### Important Understanding

The kernel does **not** calculate only once.

It slides across the image and performs the same multiply-and-add operation at every valid position.

So:

**One kernel → one feature map**

Multiple kernels can produce multiple feature maps.

This is how a CNN extracts different patterns from an image.

In [15]:
## Complete NumPy Implementation

import numpy as np

# Input image
image = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Kernel
kernel = np.array([
    [1, 0],
    [0, 1]
])

# Output size
output_size = image.shape[0] - kernel.shape[0] + 1

# Create feature map
feature_map = np.zeros((output_size, output_size))

# Convolution
for i in range(output_size):
    for j in range(output_size):

        # Select image region
        region = image[
            i:i + kernel.shape[0],
            j:j + kernel.shape[1]
        ]

        # Multiply and add
        feature_map[i, j] = np.sum(region * kernel)

print("Input Image:")
print(image)

print("\nKernel:")
print(kernel)

print("\nFeature Map:")
print(feature_map)

Input Image:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Kernel:
[[1 0]
 [0 1]]

Feature Map:
[[ 6.  8.]
 [12. 14.]]


```

### Output

```text
Input Image:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Kernel:
[[1 0]
 [0 1]]

Feature Map:
[[ 6.  8.]
 [12. 14.]]
```

The complete CNN idea we have learned is:

```text
Image
  ↓
Pixels
  ↓
Channels
  ↓
Image Tensor
  ↓
Kernel / Filter
  ↓
Convolution
  ↓
Feature Map
  ↓
Pooling
  ↓
Flattening
  ↓
Fully Connected Layer
  ↓
Prediction
```

This manual NumPy example is especially important because it shows what happens **inside a convolution operation**, rather than treating `Conv2d` as a black box